FROM openjdk:8
VOLUME /tmp
ADD build/libs/cx-flow-cmd-1.0.1.jar //
ENTRYPOINT ["/usr/bin/java"]
CMD ["-Xms512m", "-Xmx2048m","-Djava.security.egd=file:/dev/./urandom", "-Dspring.profiles.active=cmd", "-jar", "/cx-flow-cmd-1.0.jar"]
