FROM openjdk:11
VOLUME /tmp
ADD build/libs/cx-flow-11-1.0.jar //
ENTRYPOINT ["/usr/bin/java"]
CMD ["-Xms256m", "-Xmx500m","-Djava.security.egd=file:/dev/./urandom", "-jar", "/cx-flow-11-1.0.jar"]
EXPOSE 8080:8080
