apiVersion: v1
kind: Service
metadata:
  name: {{ include "cxflow.fullname" . }}
  labels:
    {{- include "cxflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
    - name: hc
      protocol: TCP
      port: 8081
      targetPort: hc
  selector:
    {{- include "cxflow.selectorLabels" . | nindent 4 }}
