//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.11.17 at 10:51:56 PM EST
//


package checkmarx.wsdl.portal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CxPredefinedCommand complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CxPredefinedCommand">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Command" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CommandType" type="{http://Checkmarx.com}CxPredefinedCommandType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CxPredefinedCommand", propOrder = {
    "name",
    "command",
    "commandType"
})
public class CxPredefinedCommand {

    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "Command")
    protected String command;
    @XmlElement(name = "CommandType", required = true)
    protected CxPredefinedCommandType commandType;

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the command property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCommand() {
        return command;
    }

    /**
     * Sets the value of the command property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCommand(String value) {
        this.command = value;
    }

    /**
     * Gets the value of the commandType property.
     *
     * @return
     *     possible object is
     *     {@link CxPredefinedCommandType }
     *
     */
    public CxPredefinedCommandType getCommandType() {
        return commandType;
    }

    /**
     * Sets the value of the commandType property.
     *
     * @param value
     *     allowed object is
     *     {@link CxPredefinedCommandType }
     *
     */
    public void setCommandType(CxPredefinedCommandType value) {
        this.commandType = value;
    }

}
