//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.11.17 at 10:51:56 PM EST
//


package checkmarx.wsdl.portal;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for CxWSReportStatusResponse complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CxWSReportStatusResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://Checkmarx.com}CxWSBasicRepsonse">
 *       &lt;sequence>
 *         &lt;element name="IsReady" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="IsFailed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CxWSReportStatusResponse", propOrder = {
    "isReady",
    "isFailed"
})
@XmlSeeAlso({
    CxWSProjectBranchingStatusResponse.class
})
public class CxWSReportStatusResponse
    extends CxWSBasicRepsonse
{

    @XmlElement(name = "IsReady")
    protected boolean isReady;
    @XmlElement(name = "IsFailed")
    protected boolean isFailed;

    /**
     * Gets the value of the isReady property.
     *
     */
    public boolean isIsReady() {
        return isReady;
    }

    /**
     * Sets the value of the isReady property.
     *
     */
    public void setIsReady(boolean value) {
        this.isReady = value;
    }

    /**
     * Gets the value of the isFailed property.
     *
     */
    public boolean isIsFailed() {
        return isFailed;
    }

    /**
     * Sets the value of the isFailed property.
     *
     */
    public void setIsFailed(boolean value) {
        this.isFailed = value;
    }

}
