//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.11.17 at 10:51:56 PM EST
//


package checkmarx.wsdl.portal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CxWSResponseSingleUserData complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CxWSResponseSingleUserData">
 *   &lt;complexContent>
 *     &lt;extension base="{http://Checkmarx.com}CxWSBasicRepsonse">
 *       &lt;sequence>
 *         &lt;element name="UserData" type="{http://Checkmarx.com}UserData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CxWSResponseSingleUserData", propOrder = {
    "userData"
})
public class CxWSResponseSingleUserData
    extends CxWSBasicRepsonse
{

    @XmlElement(name = "UserData")
    protected UserData userData;

    /**
     * Gets the value of the userData property.
     *
     * @return
     *     possible object is
     *     {@link UserData }
     *
     */
    public UserData getUserData() {
        return userData;
    }

    /**
     * Sets the value of the userData property.
     *
     * @param value
     *     allowed object is
     *     {@link UserData }
     *
     */
    public void setUserData(UserData value) {
        this.userData = value;
    }

}
