//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.11.17 at 10:51:56 PM EST
//


package checkmarx.wsdl.portal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CxWSLdapGroupMapping complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CxWSLdapGroupMapping">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LdapServerId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="LdapGroup" type="{http://Checkmarx.com}CxWSLdapGroup" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CxWSLdapGroupMapping", propOrder = {
    "ldapServerId",
    "ldapGroup"
})
public class CxWSLdapGroupMapping {

    @XmlElement(name = "LdapServerId")
    protected int ldapServerId;
    @XmlElement(name = "LdapGroup")
    protected CxWSLdapGroup ldapGroup;

    /**
     * Gets the value of the ldapServerId property.
     *
     */
    public int getLdapServerId() {
        return ldapServerId;
    }

    /**
     * Sets the value of the ldapServerId property.
     *
     */
    public void setLdapServerId(int value) {
        this.ldapServerId = value;
    }

    /**
     * Gets the value of the ldapGroup property.
     *
     * @return
     *     possible object is
     *     {@link CxWSLdapGroup }
     *
     */
    public CxWSLdapGroup getLdapGroup() {
        return ldapGroup;
    }

    /**
     * Sets the value of the ldapGroup property.
     *
     * @param value
     *     allowed object is
     *     {@link CxWSLdapGroup }
     *
     */
    public void setLdapGroup(CxWSLdapGroup value) {
        this.ldapGroup = value;
    }

}
