//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.06.07 at 11:08:45 PM EST
//


package checkmarx.wsdl.portal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CxWSResponceScanCompareResults complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CxWSResponceScanCompareResults">
 *   &lt;complexContent>
 *     &lt;extension base="{http://Checkmarx.com}CxWSBasicRepsonse">
 *       &lt;sequence>
 *         &lt;element name="Results" type="{http://Checkmarx.com}ArrayOfCxWSSingleResultCompareData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CxWSResponceScanCompareResults", propOrder = {
    "results"
})
public class CxWSResponceScanCompareResults
    extends CxWSBasicRepsonse
{

    @XmlElement(name = "Results")
    protected ArrayOfCxWSSingleResultCompareData results;

    /**
     * Gets the value of the results property.
     *
     * @return
     *     possible object is
     *     {@link ArrayOfCxWSSingleResultCompareData }
     *
     */
    public ArrayOfCxWSSingleResultCompareData getResults() {
        return results;
    }

    /**
     * Sets the value of the results property.
     *
     * @param value
     *     allowed object is
     *     {@link ArrayOfCxWSSingleResultCompareData }
     *
     */
    public void setResults(ArrayOfCxWSSingleResultCompareData value) {
        this.results = value;
    }

}
