//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.11.17 at 10:51:56 PM EST
//


package checkmarx.wsdl.portal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CxWSResponsProjectProperties complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CxWSResponsProjectProperties">
 *   &lt;complexContent>
 *     &lt;extension base="{http://Checkmarx.com}CxWSBasicRepsonse">
 *       &lt;sequence>
 *         &lt;element name="ProjectConfig" type="{http://Checkmarx.com}CxWSResponseProjectConfig" minOccurs="0"/>
 *         &lt;element name="ProjectChartData" type="{http://Checkmarx.com}CxWSResponsProjectChartData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CxWSResponsProjectProperties", propOrder = {
    "projectConfig",
    "projectChartData"
})
public class CxWSResponsProjectProperties
    extends CxWSBasicRepsonse
{

    @XmlElement(name = "ProjectConfig")
    protected CxWSResponseProjectConfig projectConfig;
    @XmlElement(name = "ProjectChartData")
    protected CxWSResponsProjectChartData projectChartData;

    /**
     * Gets the value of the projectConfig property.
     *
     * @return
     *     possible object is
     *     {@link CxWSResponseProjectConfig }
     *
     */
    public CxWSResponseProjectConfig getProjectConfig() {
        return projectConfig;
    }

    /**
     * Sets the value of the projectConfig property.
     *
     * @param value
     *     allowed object is
     *     {@link CxWSResponseProjectConfig }
     *
     */
    public void setProjectConfig(CxWSResponseProjectConfig value) {
        this.projectConfig = value;
    }

    /**
     * Gets the value of the projectChartData property.
     *
     * @return
     *     possible object is
     *     {@link CxWSResponsProjectChartData }
     *
     */
    public CxWSResponsProjectChartData getProjectChartData() {
        return projectChartData;
    }

    /**
     * Sets the value of the projectChartData property.
     *
     * @param value
     *     allowed object is
     *     {@link CxWSResponsProjectChartData }
     *
     */
    public void setProjectChartData(CxWSResponsProjectChartData value) {
        this.projectChartData = value;
    }

}
