//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.11.17 at 10:51:56 PM EST
//


package checkmarx.wsdl.portal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CxWSEnableCRUDAction complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CxWSEnableCRUDAction">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Type" type="{http://Checkmarx.com}CxWSCrudEnum"/>
 *         &lt;element name="Enable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CxWSEnableCRUDAction", propOrder = {
    "type",
    "enable"
})
public class CxWSEnableCRUDAction {

    @XmlElement(name = "Type", required = true)
    protected CxWSCrudEnum type;
    @XmlElement(name = "Enable")
    protected boolean enable;

    /**
     * Gets the value of the type property.
     *
     * @return
     *     possible object is
     *     {@link CxWSCrudEnum }
     *
     */
    public CxWSCrudEnum getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value
     *     allowed object is
     *     {@link CxWSCrudEnum }
     *
     */
    public void setType(CxWSCrudEnum value) {
        this.type = value;
    }

    /**
     * Gets the value of the enable property.
     *
     */
    public boolean isEnable() {
        return enable;
    }

    /**
     * Sets the value of the enable property.
     *
     */
    public void setEnable(boolean value) {
        this.enable = value;
    }

}
