//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.11.17 at 10:51:56 PM EST
//


package checkmarx.wsdl.portal;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GetResultsForScanByLanguageResult" type="{http://Checkmarx.com}CxWSResponceScanResults" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getResultsForScanByLanguageResult"
})
@XmlRootElement(name = "GetResultsForScanByLanguageResponse")
public class GetResultsForScanByLanguageResponse {

    @XmlElement(name = "GetResultsForScanByLanguageResult")
    protected CxWSResponceScanResults getResultsForScanByLanguageResult;

    /**
     * Gets the value of the getResultsForScanByLanguageResult property.
     *
     * @return
     *     possible object is
     *     {@link CxWSResponceScanResults }
     *
     */
    public CxWSResponceScanResults getGetResultsForScanByLanguageResult() {
        return getResultsForScanByLanguageResult;
    }

    /**
     * Sets the value of the getResultsForScanByLanguageResult property.
     *
     * @param value
     *     allowed object is
     *     {@link CxWSResponceScanResults }
     *
     */
    public void setGetResultsForScanByLanguageResult(CxWSResponceScanResults value) {
        this.getResultsForScanByLanguageResult = value;
    }

}
