//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.11.17 at 10:51:56 PM EST
//


package checkmarx.wsdl.portal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HierarchyGroupNode complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="HierarchyGroupNode">
 *   &lt;complexContent>
 *     &lt;extension base="{http://Checkmarx.com}Group">
 *       &lt;sequence>
 *         &lt;element name="Childs" type="{http://Checkmarx.com}ArrayOfHierarchyGroupNode" minOccurs="0"/>
 *         &lt;element name="Membership" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HierarchyGroupNode", propOrder = {
    "childs",
    "membership"
})
public class HierarchyGroupNode
    extends Group
{

    @XmlElement(name = "Childs")
    protected ArrayOfHierarchyGroupNode childs;
    @XmlElement(name = "Membership")
    protected boolean membership;

    /**
     * Gets the value of the childs property.
     *
     * @return
     *     possible object is
     *     {@link ArrayOfHierarchyGroupNode }
     *
     */
    public ArrayOfHierarchyGroupNode getChilds() {
        return childs;
    }

    /**
     * Sets the value of the childs property.
     *
     * @param value
     *     allowed object is
     *     {@link ArrayOfHierarchyGroupNode }
     *
     */
    public void setChilds(ArrayOfHierarchyGroupNode value) {
        this.childs = value;
    }

    /**
     * Gets the value of the membership property.
     *
     */
    public boolean isMembership() {
        return membership;
    }

    /**
     * Sets the value of the membership property.
     *
     */
    public void setMembership(boolean value) {
        this.membership = value;
    }

}
