//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.11.17 at 10:51:56 PM EST
//


package checkmarx.wsdl.portal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InstallationSetting complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="InstallationSetting">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DNSName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Hotfix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InstllationPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IsInstalled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InstallationSetting", propOrder = {
    "name",
    "id",
    "dnsName",
    "ip",
    "state",
    "version",
    "hotfix",
    "instllationPath",
    "isInstalled"
})
public class InstallationSetting {

    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "ID")
    protected String id;
    @XmlElement(name = "DNSName")
    protected String dnsName;
    @XmlElement(name = "IP")
    protected String ip;
    @XmlElement(name = "State")
    protected String state;
    @XmlElement(name = "Version")
    protected String version;
    @XmlElement(name = "Hotfix")
    protected String hotfix;
    @XmlElement(name = "InstllationPath")
    protected String instllationPath;
    @XmlElement(name = "IsInstalled")
    protected boolean isInstalled;

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the dnsName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDNSName() {
        return dnsName;
    }

    /**
     * Sets the value of the dnsName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDNSName(String value) {
        this.dnsName = value;
    }

    /**
     * Gets the value of the ip property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getIP() {
        return ip;
    }

    /**
     * Sets the value of the ip property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setIP(String value) {
        this.ip = value;
    }

    /**
     * Gets the value of the state property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the version property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the hotfix property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getHotfix() {
        return hotfix;
    }

    /**
     * Sets the value of the hotfix property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setHotfix(String value) {
        this.hotfix = value;
    }

    /**
     * Gets the value of the instllationPath property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getInstllationPath() {
        return instllationPath;
    }

    /**
     * Sets the value of the instllationPath property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setInstllationPath(String value) {
        this.instllationPath = value;
    }

    /**
     * Gets the value of the isInstalled property.
     *
     */
    public boolean isIsInstalled() {
        return isInstalled;
    }

    /**
     * Sets the value of the isInstalled property.
     *
     */
    public void setIsInstalled(boolean value) {
        this.isInstalled = value;
    }

}
