//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.11.17 at 10:51:56 PM EST
//


package checkmarx.wsdl.portal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResultState complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ResultState">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ResultName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ResultID" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResultState", propOrder = {
    "resultName",
    "resultID"
})
public class ResultState {

    @XmlElement(name = "ResultName")
    protected String resultName;
    @XmlElement(name = "ResultID")
    protected long resultID;

    /**
     * Gets the value of the resultName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getResultName() {
        return resultName;
    }

    /**
     * Sets the value of the resultName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setResultName(String value) {
        this.resultName = value;
    }

    /**
     * Gets the value of the resultID property.
     *
     */
    public long getResultID() {
        return resultID;
    }

    /**
     * Sets the value of the resultID property.
     *
     */
    public void setResultID(long value) {
        this.resultID = value;
    }

}
