//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.06.07 at 11:08:45 PM EST
//


package checkmarx.wsdl.portal;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ScanActionType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ScanActionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="EmailNotification"/>
 *     &lt;enumeration value="PostScanAction"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "ScanActionType")
@XmlEnum
public enum ScanActionType {

    @XmlEnumValue("EmailNotification")
    EMAIL_NOTIFICATION("EmailNotification"),
    @XmlEnumValue("PostScanAction")
    POST_SCAN_ACTION("PostScanAction");
    private final String value;

    ScanActionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ScanActionType fromValue(String v) {
        for (ScanActionType c: ScanActionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
