//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.06.07 at 11:08:45 PM EST
//


package checkmarx.wsdl.portal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sessionID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="userID" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="unsubscribedGroups" type="{http://Checkmarx.com}ArrayOfGroup" minOccurs="0"/>
 *         &lt;element name="subscribedGroups" type="{http://Checkmarx.com}ArrayOfGroup" minOccurs="0"/>
 *         &lt;element name="role" type="{http://Checkmarx.com}Role" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sessionID",
    "userID",
    "unsubscribedGroups",
    "subscribedGroups",
    "role"
})
@XmlRootElement(name = "UpdateUserGroups")
public class UpdateUserGroups {

    protected String sessionID;
    protected long userID;
    protected ArrayOfGroup unsubscribedGroups;
    protected ArrayOfGroup subscribedGroups;
    protected Role role;

    /**
     * Gets the value of the sessionID property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSessionID() {
        return sessionID;
    }

    /**
     * Sets the value of the sessionID property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSessionID(String value) {
        this.sessionID = value;
    }

    /**
     * Gets the value of the userID property.
     *
     */
    public long getUserID() {
        return userID;
    }

    /**
     * Sets the value of the userID property.
     *
     */
    public void setUserID(long value) {
        this.userID = value;
    }

    /**
     * Gets the value of the unsubscribedGroups property.
     *
     * @return
     *     possible object is
     *     {@link ArrayOfGroup }
     *
     */
    public ArrayOfGroup getUnsubscribedGroups() {
        return unsubscribedGroups;
    }

    /**
     * Sets the value of the unsubscribedGroups property.
     *
     * @param value
     *     allowed object is
     *     {@link ArrayOfGroup }
     *
     */
    public void setUnsubscribedGroups(ArrayOfGroup value) {
        this.unsubscribedGroups = value;
    }

    /**
     * Gets the value of the subscribedGroups property.
     *
     * @return
     *     possible object is
     *     {@link ArrayOfGroup }
     *
     */
    public ArrayOfGroup getSubscribedGroups() {
        return subscribedGroups;
    }

    /**
     * Sets the value of the subscribedGroups property.
     *
     * @param value
     *     allowed object is
     *     {@link ArrayOfGroup }
     *
     */
    public void setSubscribedGroups(ArrayOfGroup value) {
        this.subscribedGroups = value;
    }

    /**
     * Gets the value of the role property.
     *
     * @return
     *     possible object is
     *     {@link Role }
     *
     */
    public Role getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     *
     * @param value
     *     allowed object is
     *     {@link Role }
     *
     */
    public void setRole(Role value) {
        this.role = value;
    }

}
