//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.11.17 at 10:51:56 PM EST
//


package checkmarx.wsdl.portal;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for WebClientApprovedUser complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="WebClientApprovedUser">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UserID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="UserName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CompanyID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ExpirationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="TeamId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LoginUrl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WebClientApprovedUser", propOrder = {
    "userID",
    "userName",
    "companyID",
    "expirationDate",
    "teamId",
    "loginUrl"
})
public class WebClientApprovedUser {

    @XmlElement(name = "UserID")
    protected int userID;
    @XmlElement(name = "UserName")
    protected String userName;
    @XmlElement(name = "CompanyID")
    protected String companyID;
    @XmlElement(name = "ExpirationDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar expirationDate;
    @XmlElement(name = "TeamId")
    protected String teamId;
    @XmlElement(name = "LoginUrl")
    protected String loginUrl;

    /**
     * Gets the value of the userID property.
     *
     */
    public int getUserID() {
        return userID;
    }

    /**
     * Sets the value of the userID property.
     *
     */
    public void setUserID(int value) {
        this.userID = value;
    }

    /**
     * Gets the value of the userName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    /**
     * Gets the value of the companyID property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCompanyID() {
        return companyID;
    }

    /**
     * Sets the value of the companyID property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCompanyID(String value) {
        this.companyID = value;
    }

    /**
     * Gets the value of the expirationDate property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getExpirationDate() {
        return expirationDate;
    }

    /**
     * Sets the value of the expirationDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setExpirationDate(XMLGregorianCalendar value) {
        this.expirationDate = value;
    }

    /**
     * Gets the value of the teamId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTeamId() {
        return teamId;
    }

    /**
     * Sets the value of the teamId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTeamId(String value) {
        this.teamId = value;
    }

    /**
     * Gets the value of the loginUrl property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLoginUrl() {
        return loginUrl;
    }

    /**
     * Sets the value of the loginUrl property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLoginUrl(String value) {
        this.loginUrl = value;
    }

}
