name: Natalies Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - develop

jobs:
  update_release_draft:
    runs-on: cx-public-ubuntu-x64
    steps:
      - uses: natalieb07/release-drafter@2da8d50c9477fc4d5b2aad284658e42564dbc4f7 # v5.12.1.6
        with:
          # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
          config-name: release-drafter.yml
          prerelease: false
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
