name: Documentation

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      # Additional steps to generate documentation in "docs" directory
      - name: Upload docs to Wiki
        uses: checkmarx-ltd/github-wiki-publish-action@master
        with:
          path: "docs"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
